### ISSUE TITLE
SelectMany causing query with no where

### ISSUE THREAD

**Issue by JohnGalt1717** [tuespetre/Impatient#2]
If you do something like this:

Users.SelectMany(u => u.Organizations).Where(o => o.Active).ToArray()

It results in a query like this:

SELECT * FROM Users

Instead of breaking it down into proper form.

**Comment by tuespetre** [comment]
@JohnGalt1717 do you have sample code to reproduce? Which versions of which libraries are you using?

Also: what type is `Users`? Is it `IQueryable<T>`, or is it `IEnumerable<T>`?

**Comment by tuespetre** [comment]
I was unable to reproduce your issue. I'm going to close this now since I haven't heard back.

**Comment by JohnGalt1717** [comment]
Sorry, even though this is excellent we had to stop using it in testing because there is no TVF nor FromSql functionality so it was a blocker.

**Comment by ahmad-moussawi** [comment]
@JohnGalt1717 what do you mean by TVF ?

**Comment by JohnGalt1717** [comment]
@ahmad-moussawi Table valued functions.

**Comment by tuespetre** [comment]
Thanks for the feedback @JohnGalt1717.

**Comment by JohnGalt1717** [comment]
@tuespetre To further this, because EF core doesn't support TVFs the only way to access them and do joins etc. is with FromSql() which works great because it will join the results nicely and do so on the server.

If [DbFunction] supported TVFs then we'd have no problem.

The issue is that there are lots of cases where single line TVFs are faster than EF Core because of if materialization penalties which is why we use them in complex cases. (especially with sub exists for security etc.)

**Comment by tuespetre** [comment]
@JohnGalt1717 I am interested to see about possible support for TVF mapping. I've managed things like querying out of a JSON string with `OPENJSON` and mapping `string.Split` to `STRING_SPLIT` already, but the biggest concern I have is that I don't know that there's a way in EF's model to stuff the metadata for the return types anywhere so it can be referenced during processing.

**Comment by JohnGalt1717** [comment]
There is an outstanding pull request here: [TVFs in EF](https://github.com/aspnet/EntityFrameworkCore/pull/11129#discussion_r199325282)
